name: Deploy Node Application

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t rampeddireddi/stormledgers-backend .

      - name: Publish Image to Docker Hub
        run: docker push rampeddireddi/stormledgers-backend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: sudo docker pull rampeddireddi/stormledgers-backend:latest

      - name: Delete old container
        run: sudo docker rm -f nodejs-app-container || true

      - name: Run Docker Container
        run: |
          docker run -d -p 4000:8000 \
          --name nodejs-app-container \
          -e MONGO_URL='${{ secrets.MONGO_URL }}' \
          -e JWT_SECRET='${{ secrets.JWT_SECRET }}' \
          -e PORT='8000' \
          -e EMAIL_HOST='${{ secrets.EMAIL_HOST }}' \
          -e EMAIL_USER='${{ secrets.EMAIL_USER }}' \
          -e EMAIL_PASS='${{ secrets.EMAIL_PASS }}' \
          -e EMAIL_PORT='${{ secrets.EMAIL_PORT }}' \
          rampeddireddi/stormledgers-backend:latest
